# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: deCrypto
# Description of the Site
description: Demystifying biology, finance and other interesting topics
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: patrick.truong@scilifelab.se     
facebook_username: patrick.truong.184
# twitter_username: /
instagram_username: ptruoong
linkedin_username: patrick-truong-768462b1
github_username:  patruong
# youtube_channel_id: /
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Patrick Truong
# URL for the Image of the Author
author-image: https://scontent-arn2-1.xx.fbcdn.net/v/t1.0-9/74449369_3347270681971677_3279608124477684482_n.jpg?_nc_cat=111&_nc_sid=09cbfe&_nc_ohc=V15UT_EL6pQAX_YwUo6&_nc_ht=scontent-arn2-1.xx&oh=50325309b615c18e298cae3eeb553f9b&oe=5F906DAD
# 60 Words About the Author
author-about: Hello, My name is Patrick Truong and I am a bioinformatics researcher and a layman swing trader. I am enthusiastic about most topics and this web page is serves as a journal in my journey to discover all thing interesting. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
